#undef PLOOPY_DPI_DEFAULT
#define PLOOPY_DPI_DEFAULT 2
#undef PLOOPY_DRAGSCROLL_INVERT
#define PLOOPY_DRAGSCROLL_INVERT 1
#undef PLOOPY_DRAGSCROLL_MULTIPLIER
#define PLOOPY_DRAGSCROLL_MULTIPLIER 0.25
